# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/tsbadamkhanov/Downloads/OperatingSystems_Lab2-master

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/tsbadamkhanov/Downloads/OperatingSystems_Lab2-master

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/tsbadamkhanov/Downloads/OperatingSystems_Lab2-master/CMakeFiles /Users/tsbadamkhanov/Downloads/OperatingSystems_Lab2-master//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/tsbadamkhanov/Downloads/OperatingSystems_Lab2-master/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lab2_cache

# Build rule for target.
lab2_cache: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lab2_cache
.PHONY : lab2_cache

# fast build rule for target.
lab2_cache/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lab2_cache.dir/build.make CMakeFiles/lab2_cache.dir/build
.PHONY : lab2_cache/fast

#=============================================================================
# Target rules for targets named writebench

# Build rule for target.
writebench: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 writebench
.PHONY : writebench

# fast build rule for target.
writebench/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/writebench.dir/build.make CMakeFiles/writebench.dir/build
.PHONY : writebench/fast

#=============================================================================
# Target rules for targets named emasearchbench

# Build rule for target.
emasearchbench: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 emasearchbench
.PHONY : emasearchbench

# fast build rule for target.
emasearchbench/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/emasearchbench.dir/build.make CMakeFiles/emasearchbench.dir/build
.PHONY : emasearchbench/fast

API/lab2_cache.o: API/lab2_cache.cpp.o
.PHONY : API/lab2_cache.o

# target to build an object file
API/lab2_cache.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lab2_cache.dir/build.make CMakeFiles/lab2_cache.dir/API/lab2_cache.cpp.o
.PHONY : API/lab2_cache.cpp.o

API/lab2_cache.i: API/lab2_cache.cpp.i
.PHONY : API/lab2_cache.i

# target to preprocess a source file
API/lab2_cache.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lab2_cache.dir/build.make CMakeFiles/lab2_cache.dir/API/lab2_cache.cpp.i
.PHONY : API/lab2_cache.cpp.i

API/lab2_cache.s: API/lab2_cache.cpp.s
.PHONY : API/lab2_cache.s

# target to generate assembly for a file
API/lab2_cache.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lab2_cache.dir/build.make CMakeFiles/lab2_cache.dir/API/lab2_cache.cpp.s
.PHONY : API/lab2_cache.cpp.s

emasearchbench.o: emasearchbench.cpp.o
.PHONY : emasearchbench.o

# target to build an object file
emasearchbench.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/emasearchbench.dir/build.make CMakeFiles/emasearchbench.dir/emasearchbench.cpp.o
.PHONY : emasearchbench.cpp.o

emasearchbench.i: emasearchbench.cpp.i
.PHONY : emasearchbench.i

# target to preprocess a source file
emasearchbench.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/emasearchbench.dir/build.make CMakeFiles/emasearchbench.dir/emasearchbench.cpp.i
.PHONY : emasearchbench.cpp.i

emasearchbench.s: emasearchbench.cpp.s
.PHONY : emasearchbench.s

# target to generate assembly for a file
emasearchbench.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/emasearchbench.dir/build.make CMakeFiles/emasearchbench.dir/emasearchbench.cpp.s
.PHONY : emasearchbench.cpp.s

writebench.o: writebench.cpp.o
.PHONY : writebench.o

# target to build an object file
writebench.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/writebench.dir/build.make CMakeFiles/writebench.dir/writebench.cpp.o
.PHONY : writebench.cpp.o

writebench.i: writebench.cpp.i
.PHONY : writebench.i

# target to preprocess a source file
writebench.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/writebench.dir/build.make CMakeFiles/writebench.dir/writebench.cpp.i
.PHONY : writebench.cpp.i

writebench.s: writebench.cpp.s
.PHONY : writebench.s

# target to generate assembly for a file
writebench.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/writebench.dir/build.make CMakeFiles/writebench.dir/writebench.cpp.s
.PHONY : writebench.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... emasearchbench"
	@echo "... lab2_cache"
	@echo "... writebench"
	@echo "... API/lab2_cache.o"
	@echo "... API/lab2_cache.i"
	@echo "... API/lab2_cache.s"
	@echo "... emasearchbench.o"
	@echo "... emasearchbench.i"
	@echo "... emasearchbench.s"
	@echo "... writebench.o"
	@echo "... writebench.i"
	@echo "... writebench.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

